[neo4j]
uri = "neo4j+s://7cbe2dae.databases.neo4j.io"
user = "8e5bfee5"
password = "5Fo70NBq8lvZV3_6o6gqB08ti0OwCM6d3K6GJcJ0j0I"
database = "7cbe2dae"

[aura]
instance_id = "8e5bfee5"
instance_name = "Free instance"
